name: Upload OpenAPI spec to Stainless

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  stainless:
    concurrency: upload-openapi-spec-action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: stainless-api/upload-openapi-spec-action@sam/gitlab-component
        with:
          stainless_api_key: ${{ secrets.STAINLESS_API_KEY }}
          input_path: "openapi.json"
          project_name: "sam"
          config_path: "sam.stainless.yaml"
          commit_message: ${{ github.event.head_commit.message }}
